export const clubsArray = [
  { name: "Real Madrid" },
  { name: "Manchester City" },
  { name: "Barcelona" },
  { name: "Paris Saint-Germain" },
  { name: "Bayern de Munique" },
  { name: "Liverpool" },
  { name: "Arsenal" },
  { name: "Inter de Milão" },
  { name: "Atlético de Madrid" },
  { name: "Bayer Leverkusen" },
  { name: "Lille" },
  { name: "Aston Villa" },
  { name: "Feyenoord" },
  { name: "Club Brugge" },
  { name: "Benfica" },
  { name: "Borussia Dortmund" },
  { name: "PSV Eindhoven" },
  { name: "Juventus" },
  { name: "Manchester United" },
  { name: "RB Leipzig" },
  { name: "Milan" },
  { name: "Celtic" },
  { name: "Monaco" },
  { name: "Shakhtar Donetsk" },
  { name: "Atalanta" },
  { name: "Dinamo Zagreb" },
  { name: "Sporting CP" },
  { name: "Sparta Praga" },
  { name: "Slovan Bratislava" },
  { name: "VfB Stuttgart" },
  { name: "Crevena Zvezda" },
  { name: "Dinamo de Kiev" },
  { name: "Olympique de Marselha" },
  { name: "Sevilla" },
  { name: "Porto" },
  { name: "Napoli" },
];
